# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(-10, 0, 811, 571))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.textLed1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textLed1.setGeometry(QtCore.QRect(60, 70, 31, 31))
        self.textLed1.setObjectName("textLed1")
        self.textLed2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textLed2.setGeometry(QtCore.QRect(60, 120, 31, 31))
        self.textLed2.setObjectName("textLed2")
        self.textLed3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textLed3.setGeometry(QtCore.QRect(60, 170, 31, 31))
        self.textLed3.setObjectName("textLed3")
        self.textLed4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textLed4.setGeometry(QtCore.QRect(60, 220, 31, 31))
        self.textLed4.setObjectName("textLed4")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(60, 270, 31, 31))
        self.pushButton1.setText("")
        self.pushButton1.setObjectName("pushButton1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 31, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 31, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 31, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 31, 17))
        self.label_6.setObjectName("label_6")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(60, 320, 31, 31))
        self.pushButton2.setText("")
        self.pushButton2.setObjectName("pushButton2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 380, 31, 17))
        self.label_7.setObjectName("label_7")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(60, 370, 31, 31))
        self.pushButton3.setText("")
        self.pushButton3.setObjectName("pushButton3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 430, 31, 17))
        self.label_8.setObjectName("label_8")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(60, 420, 31, 31))
        self.pushButton4.setText("")
        self.pushButton4.setObjectName("pushButton4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuNew.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "  virtualization board"))
        self.label.setText(_translate("MainWindow", "led1"))
        self.label_2.setText(_translate("MainWindow", "led2"))
        self.label_3.setText(_translate("MainWindow", "led3"))
        self.label_4.setText(_translate("MainWindow", "led4"))
        self.label_5.setText(_translate("MainWindow", "key1"))
        self.label_6.setText(_translate("MainWindow", "key2"))
        self.label_7.setText(_translate("MainWindow", "key3"))
        self.label_8.setText(_translate("MainWindow", "key4"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))

